<h2>Add New Book</h2>
<?php
echo $this->form;
?>
<!-- <div class="row">
	<div class="col-md-6">
		<form action="" method="post">
			<table class="table">
				<tr>
					<td>Name : </td>
					<td><input type="text" name="" id="input" class="form-control" value="" required="required" pattern="" title=""></td>
				</tr>
				<tr>
					<td>Email : </td>
					<td><input type="text" name="" id="input" class="form-control" value="" required="required" pattern="" title=""></td>
				</tr>
				<tr>
					<td>Address : </td>
					<td><input type="text" name="" id="input" class="form-control" value="" required="required" pattern="" title=""></td>
				</tr>
				<tr>
					<td>Mobile : </td>
					<td><input type="text" name="" id="input" class="form-control" value="" required="required" pattern="" title=""></td>
				</tr>
				<tr>
					<td></td>
					<td><input type="submit" name="addnow" id="addnow" value="Add now" ></td>
				</tr>
			</table>
		</form>
	</div>
</div> -->