<?php
	$stt = 1;
?>
<div class="row">
    <ol class="breadcrumb">
        <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
        <li class="active">Users Manager</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Users Management</h1>
    </div>
</div><!-- /.row -->
<table class="table" width="600px;">
	<thead>
		<th>#</th>
		<th>Name</th>
		<th>Email</th>
		<th>Address</th>
		<th>Mobile phone</th>
		<th>Options</th>
	</thead>
	<tbody>
		<?php foreach ($this->allUsers as $key => $item) { ?>
			<tr>
				<td><?=  $stt++ ?> </td>
				<td><?=  $item['name'] ?> </td>
				<td><?=  $item['email'] ?> </td>
				<td><?=  $item['address'] ?> </td>
				<td><?=  $item['mobile'] ?> </td>
				<td><a class="btn btn-info" href="<?php  echo $this->url(array('controller'=>'users','action'=>'edit','id'=>$item['id'])) ?>" >Edit</a>
					<a class="btn btn-danger" href="<?php  echo $this->url(array('controller'=>'users','action'=>'remove','id'=>$item['id'])) ?>" >Remove</a>
				</td>
			</tr>
		<?php
			}
		?>
		
	</tbody>
</table>
<br>
<a class="btn btn-success" href="<?php  echo $this->url(array('controller'=>'users','action'=>'add')) ?>" >Add New Book</a>